[package]
name = "bitis_msgs"
version = "0.10.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bitis_msgs"
crate-type = ["cdylib"]



[dependencies]
pyo3 = "0.24.0"
bitis = "0.6.4"
