[package]
name = "py_msg"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_msg"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
bitis= {path = "../../../.."}
array-init = "2.1.0"
