[package]
name = "test_simple"
version = "0.9.4"
edition = "2024"

[[bin]]
name = "rust_impl"
path = "src/main.rs"


[dependencies]
#bitis = { version = "0.6.5" }
bitis = {path = "../../../"}
array-init = "2.1.0"
ascii = "1.1.0"

